Lint PowerShell in workflows
Lint the inline PowerShell scripts in the GitHub Actions workflows.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -50,4 +50,55 @@ jobs:
 
     - name: Lint PowerShell
       shell: pwsh
-      run: Invoke-ScriptAnalyzer -Path . -Recurse -IncludeDefaultRules -ReportSummary -Severity @('Error','Warning') -EnableExit
+      run: |
+        Invoke-ScriptAnalyzer -Path . -Recurse -IncludeDefaultRules -ReportSummary -Severity @('Error','Warning') -EnableExit
+
+        $POWERSHELL_YAML_VERSION = "0.4.12"
+        Install-Module -Name powershell-yaml -Force -MaximumVersion ${env:POWERSHELL_YAML_VERSION}
+
+        $files = @()
+        $files += Get-ChildItem -Path .github/workflows -Filter *.yml -Recurse
+        $files += Get-ChildItem -Path .github/workflows -Filter *.yaml -Recurse
+
+        $hasErrors = $false
+
+        foreach ($file in $files) {
+            $path = $file.FullName
+            $content = Get-Content -Path $file.FullName -Raw
+
+            $fileName = $path.Substring($PWD.Path.Length + 1).Replace('\', '/')
+            $workflow = ConvertFrom-Yaml -Yaml $content
+
+            Write-Output "Linting ${fileName}..."
+
+            $errors = 0
+            $warnings = 0
+
+            foreach ($job in $workflow.jobs) {
+                foreach ($step in $job.Values.steps) {
+                    if ($step.run -And $step.shell -eq 'pwsh') {
+                        $script = $step.run
+
+                        $firstLine = $script.Split("`n")[0]
+                        $offset    = (Select-String $path -Pattern ([regex]::Escape($firstLine))).LineNumber
+
+                        $issues = Invoke-ScriptAnalyzer -ScriptDefinition $script -IncludeDefaultRules -Severity @('Error','Warning')
+
+                        $errors   += $issues.Where({$_.Severity -eq 'Error' -or $_.Severity -eq 'ParseError'}).Count
+                        $warnings += $issues.Count - $errors
+
+                        foreach ($issue in $issues) {
+                            $level = $issue.Severity -eq "Warning" ? "warning" : "error"
+                            $line = $offset + $issue.Line - 1
+                            Write-Output "::${level} file=${fileName},line=${line},title=PSScriptAnalyzer::${issue}"
+                        }
+                    }
+                }
+            }
+
+            Write-Output "Errors: $($errors); Warnings: $($warnings)."
+        }
+
+        if ($hasErrors) {
+            exit 1
+        }
